name: Acorn Windows Installer
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --deploy --dev
        pipenv run pip install pyinstaller

    - name: Build executable with PyInstaller
      run: |
        pipenv run pyinstaller --windowed --add-data "src/imgs/*;imgs" --icon "src/imgs/acorn.ico" --name acorn main.py

    - name: Verify executable exists
      run: |
        if (!(Test-Path "dist/acorn/acorn.exe")) {
          throw "acorn.exe not found"
        }

    - name: Create Inno Setup script
      run: |
        $script = @'
        [Setup]
        AppName=Acorn
        AppVersion=0.3.0
        AppVerName=Acorn
        AppPublisher=Acorn
        AppId={{ACORN-UNIQUE-ID}}
        DefaultDirName={pf}\Acorn
        DefaultGroupName=Acorn
        OutputBaseFilename=acorn-installer
        OutputDir=Output
        Compression=lzma
        SolidCompression=yes
        PrivilegesRequired=admin
        ArchitecturesInstallIn64BitMode=x64
        ArchitecturesAllowed=x86 x64
        UninstallDisplayIcon={app}\acorn.exe
        DisableProgramGroupPage=yes
        WizardStyle=modern

        [Files]
        Source: "dist\acorn\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs

        [Icons]
        Name: "{group}\Acorn"; Filename: "{app}\acorn.exe"
        Name: "{commondesktop}\Acorn"; Filename: "{app}\acorn.exe"; Tasks: desktopicon
        Name: "{group}\Uninstall Acorn"; Filename: "{uninstallexe}"

        [Tasks]
        Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional icons:"; Flags: unchecked

        [Registry]
        Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "Acorn"; ValueData: """{app}\acorn.exe"""; Flags: uninsdeletevalue

        [UninstallDelete]
        Type: filesandordirs; Name: "{app}"
        '@
        Set-Content -Path installer.iss -Value $script -Encoding Ascii

    - name: Compile Installer
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
      with:
        path: installer.iss
        options: /O+

    - name: Upload installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: acorn-installer.exe
        path: Output/acorn-installer.exe
