name: Acorn Windows Installer
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --deploy --dev
        pipenv run pip install pyinstaller

    - name: Build executable with PyInstaller
      run: |
        pipenv run pyinstaller --windowed --add-data "src/imgs/*;imgs" --icon "src/imgs/acorn.ico" --name acorn main.py

    - name: Verify executable exists
      run: |
        if (!(Test-Path "dist/acorn/acorn.exe")) {
          throw "acorn.exe not found"
        }

    - name: Install Inno Setup
      run: choco install innosetup --no-progress

    - name: Create Inno Setup script
      shell: cmd
      run: |
        > installer.iss (
          echo [Setup]
          echo AppName=Acorn
          echo AppVersion=0.3.0
          echo AppVerName=Acorn
          echo AppPublisher=Acorn
          echo AppId={{ACORN-UNIQUE-ID}}
          echo DefaultDirName={pf}\Acorn
          echo DefaultGroupName=Acorn
          echo OutputBaseFilename=acorn-installer
          echo OutputDir=Output
          echo Compression=lzma
          echo SolidCompression=yes
          echo PrivilegesRequired=admin
          echo ArchitecturesInstallIn64BitMode=x64
          echo ArchitecturesAllowed=x86 x64
          echo UninstallDisplayIcon={app}\acorn.exe
          echo DisableProgramGroupPage=yes
          echo WizardStyle=modern

          echo [Files]
          echo Source: "dist\acorn\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs

          echo [Icons]
          echo Name: "{group}\Acorn"; Filename: "{app}\acorn.exe"
          echo Name: "{commondesktop}\Acorn"; Filename: "{app}\acorn.exe"; Tasks: desktopicon
          echo Name: "{group}\Uninstall Acorn"; Filename: "{uninstallexe}"

          echo [Tasks]
          echo Name: "desktopicon"; Description: "Create a ^&desktop shortcut"; GroupDescription: "Additional icons:"; Flags: unchecked

          echo [Registry]
          echo Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "Acorn"; ValueData: """{app}\acorn.exe"""; Flags: uninsdeletevalue

          echo [UninstallDelete]
          echo Type: filesandordirs; Name: "{app}"
        )

    - name: Build installer
      run: |
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: acorn-installer
        path: Output/acorn-installer.exe
